#+TITLE: Doom configuration

* Identity information
#+BEGIN_SRC elisp
(setq user-full-name "David Lewis"
      user-mail-address "davidalewis00@gmail.com")
#+END_SRC
* Theme
set theme with doom-theme or load theme with load-theme
#+BEGIN_SRC elisp
(setq doom-theme 'doom-gruvbox)
#+END_SRC
* Org Setup
** Org Directory
#+BEGIN_SRC elisp
(setq org-directory "~/Dropbox/org/")
#+END_SRC
** Hide emphasis markers
#+BEGIN_SRC elisp
(setq org-hide-emphasis-markers 't)
#+END_SRC
** Org Tab behaviour
  #+BEGIN_SRC elisp
  (after! evil-org
    (setq org-tab-first-hook nil))
  #+END_SRC
** org code blocks
#+begin_src elisp
(defun insert-jupyter-block ()
  "Inserts a python code block"
  (interactive)
  (progn
    (insert "#+begin_src jupyter-python :session py\n"
            "#+end_src")
    )
  )
#+end_src
** Functions
#+begin_src elisp
(defun cache-address ()
 (interactive)
 (progn
   (setq size (read-string "Enter the MM size: "))
   (setq strunit (substring size -2 nil))
   (if (eq (compare-strings strunit nil nil "GB" nil nil) 't)
       (message "true"))
 )
 )
#+end_src

#+RESULTS:
: cache-address

** org keymap
#+begin_src elisp
(map! (:map org-mode-map
       :localleader
       (:prefix ("S" . "source")
        :desc "jupyter-python" "p" #'insert-jupyter-block)))
#+end_src

#+RESULTS:

* Python setup

** Anaconda directory
#+begin_src elisp
(setq conda-anaconda-home "~/.conda")
#+end_src

* General configuration
** remove line numbers
#+Begin_SRC elisp
(setq display-line-numbers-type nil)
#+END_SRC
** Fix treemacs ace-window bug
#+BEGIN_SRC elisp
(require 'ace-window)
#+END_SRC
** deletes compilation buffer if successful (ignores python buffers)
#+BEGIN_SRC elisp
(add-hook 'compilation-finish-functions
          (lambda(buffer string)
            (if (and (null (string-match ".*exited abnormally.*" string))
                     (null(eq major-mode 'inferior-python-mode)))
                ;; make compilation window go away after a few seconds
                (progn
                  (run-at-time
                   "1 sec" nil 'delete-windows-on
                   (get-buffer-create "*compilation*"))
                  (print major-mode)
                  (message "Compilation finished successfully")))))
#+END_SRC
* Key Map
** General Buffers
#+BEGIN_SRC elisp
(map! :leader
      :desc "treemacs" "0" #'treemacs
      :desc "last-buffer" "l" #'evil-switch-to-windows-last-buffer
      :nv "`" nil
      (:prefix ("w")
       :desc "ace-window" "a" #'ace-window))
#+END_SRC
** Python mode map
#+BEGIN_SRC elisp
(map!  (:map python-mode-map
        :localleader
        :desc "repl" "'" #'+python/open-ipython-repl
        (:prefix ("s" . "send")
         :desc "buffer" "b" #'python-shell-send-buffer
         :desc "function" "f" #'python-shell-send-defun
         :desc "region" "r" #'python-shell-send-region
         :desc "statement" "s" #'python-shell-send-statement)))
#+END_SRC
** Doc-view mode map
#+BEGIN_SRC elisp
(map! (:map doc-view-mode-map
       :nv "l" #'doc-view-next-page
       :nv "h" #'doc-view-previous-page))
#+END_SRC
** mips mode map
#+BEGIN_SRC elisp
(map! (:map mips-mode-map
       :localleader
       (:prefix ("s" . "send")
        :desc "file" "f" #'mips-run-file
        :desc "region" "r" #'mips-run-region
        :desc "buffer" "b" #'mips-run-region)))
#+END_SRC
* Helpful info
** Font variables
+ doom-font (normal font)
+ doom-variable-pitch-font (easy reading font)
+ doom-big-font (doom-big-font-mode for presentations)
** Useful customization functions
+ load! (load external .el files)
+ use-package! (for configuring packages)
+ after! (runs config after packages has loaded)
+ add-load-path! (adds directories to load-path variable)
+ map! (binds keys)
